<?php
declare(strict_types=1);

return [
	'GET' => [
		'/' => ['DashboardController', 'index'],
		'/login' => ['AuthController', 'showLogin'],
		'/dashboard' => ['DashboardController', 'index'],
		'/requests' => ['RequestController', 'index'],
		'/purchases' => ['PurchaseController', 'index'],
		'/deliveries' => ['DeliveryController', 'index'],
		'/reports' => ['ReportsController', 'index'],
		'/reports/export/excel' => ['ReportsController', 'excel'],
		'/reports/export/csv' => ['ReportsController', 'csv'],
		'/audit' => ['AuditController', 'index'],
		'/notifications' => ['NotificationController', 'index'],
		'/reports/pdf' => ['ReportsController', 'pdf'],
		'/inventory' => ['InventoryController', 'index'],
		'/inventory/import' => ['InventoryController', 'import'],
		'/users' => ['UserController', 'index'],
		'/admin/settings' => ['AdminSettingsController', 'index'],
		'/account/security' => ['AccountController', 'security'],
	],
	'POST' => [
		'/login' => ['AuthController', 'login'],
		'/logout' => ['AuthController', 'logout'],
		'/requests' => ['RequestController', 'store'],
		'/requests/approve' => ['RequestController', 'approve'],
		'/requests/reject' => ['RequestController', 'reject'],
		'/requests/update' => ['RequestController', 'update'],
		'/requests/delete' => ['RequestController', 'delete'],
		'/requests/distribute' => ['RequestController', 'distribute'],
		'/requests/prepare' => ['RequestController', 'prepare'],
		'/purchases' => ['PurchaseController', 'store'],
		'/purchases/mark-paid' => ['PurchaseController', 'markPaid'],
		'/deliveries' => ['DeliveryController', 'store'],
		// removed force-delete feature routes
		'/inventory' => ['InventoryController', 'store'],
		'/inventory/import' => ['InventoryController', 'import'],
		'/inventory/meta' => ['InventoryController', 'updateMeta'],
		'/inventory/set' => ['InventoryController', 'storeSet'],
		'/inventory/set/delete' => ['InventoryController', 'deleteSet'],
		'/users' => ['UserController', 'store'],
		'/users/update' => ['UserController', 'update'],
		'/users/delete' => ['UserController', 'delete'],
		'/users/reset-password' => ['UserController', 'resetPassword'],
		'/notifications' => ['NotificationController', 'index'],
		'/audit/clear' => ['AuditController', 'clear'],
		'/admin/settings/save' => ['AdminSettingsController', 'save'],
		'/admin/settings/branding' => ['AdminSettingsController', 'updateBranding'],
		'/admin/settings/backup/export' => ['AdminSettingsController', 'exportBackup'],
		'/admin/settings/backup/import' => ['AdminSettingsController', 'importInventory'],
		'/admin/settings/users/status' => ['AdminSettingsController', 'toggleUserStatus'],
		'/admin/settings/users/force-logout' => ['AdminSettingsController', 'forceLogoutUser'],
		'/account/security/password' => ['AccountController', 'updatePassword'],
		'/account/theme' => ['AccountController', 'updateTheme'],
	],
];

